name: CI - Test bn Utility

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build convert executable
      run: make

    - name: Build ctest executable
      run: make ctest

    - name: Run Tests
      run: ./test_script > test_results.txt

    - name: Run gcov
      run: |
        gcov *.c
        mv *.gcov coverage/

    - name: Upload convert executable
      uses: actions/upload-artifact@v4
      with:
        name: Convert Executable
        path: ./convert

    - name: Upload Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: ./test_results.txt

    - name: Upload Coverage Reports
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Reports
        path: ./coverage/*.gcov
