name: CI Pipeline for convert.c

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build convert
      run: make

    - name: Upload convert executable
      uses: actions/upload-artifact@v4
      with:
        name: Convert Executable
        path: ./convert

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build ctest with coverage
      run: gcc --coverage -o ctest convert.c convert_to_base.c

    - name: Run tests and generate coverage
      run: |
        chmod +x test_script
        ./test_script
        gcov convert.c convert_to_base.c

    - name: Upload test results and coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: Test Results and Coverage
        path: |
          ./test_results.txt
          ./convert.c.gcov
          ./convert_to_base.c.gcov
