name: CI - Test convert Utility

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build convert
      run: make

    - name: Build ctest with coverage
      run: make ctest

    - name: Run Tests
      run: make ctest; ./test_script > test_results.txt; gcov ctest-convert.c

    - name: Upload Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: ./test_results.txt

    - name: Upload Coverage Reports
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Reports
        path: |
          ./ctest-convert.c.gcov
