name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build convert
      run: make convert

    - name: Upload convert executable
      uses: actions/upload-artifact@v4
      with:
        name: convert
        path: ./convert

    - name: Build ctest executable with coverage and run tests
      run: |
        make ctest
        ./test_script > test_results.txt
        gcov ctest-convert.c

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test_results.txt

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: ctest-convert.c.gcov
